apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.config.name }}
  labels:
    app: app
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
type: Opaque
data:
  username: {{ .Values.secrets.username | b64enc | quote }}