---

- name: Create a new directory
  file:
    path: /opt/app
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /opt/app/docker-compose.yml
    owner: root

- name: Run docker-compose
  docker_compose:
    project_src: /opt/app
    state: present
    pull: true